import {render} from './preview-renderer.mjs';
const copy=v=>structuredClone(v),escapeHTML=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
window.results={dialogs:[],messages:[],notifications:[],created:[]};
class Collection extends Array{get contents(){return this;}get(id){return this.find(x=>x.id===id);}static get [Symbol.species](){return Array;}}
class App{constructor(options={}){this.options=options;this.actor=options.actor;}async _prepareContext(){return {};}async _onRender(){}async submit(){}bringToFront(){}async close(){this.closed=true;}render(){this.ready=(async()=>{const ctx=await this._prepareContext({});const template=await(await fetch(this.constructor.PARTS.main.template)).text();const outer=document.querySelector('#app');outer.className='application '+(this.constructor.DEFAULT_OPTIONS.classes??[]).join(' ');outer.style.width=(this.constructor.DEFAULT_OPTIONS.position?.width??1000)+'px';outer.style.height=(this.constructor.DEFAULT_OPTIONS.position?.height??800)+'px';outer.innerHTML='<div class="window-content">'+render(template,ctx)+'</div>';this.element=outer;outer.onclick=async event=>{const target=event.target.closest('[data-action]');if(target&&!target.disabled){const action=this.constructor.DEFAULT_OPTIONS.actions?.[target.dataset.action];if(action)await action.call(this,event,target);}};await this._onRender(ctx,{});window.current=this;})();return this;}}
class ActorDirectory{}
window.foundry={utils:{deepClone:copy,escapeHTML},applications:{api:{ApplicationV2:App,HandlebarsApplicationMixin:c=>c,DialogV2:{input:async data=>{results.dialogs.push(data);return window.dialogInput??null;},confirm:async data=>{results.dialogs.push(data);return window.acceptConfirm??false;}}},sheets:{ActorSheetV2:App,ItemSheetV2:App},sidebar:{tabs:{ActorDirectory}}}};
window.ui={notifications:Object.fromEntries(['info','warn','error'].map(k=>[k,s=>results.notifications.push({kind:k,text:s})]))};
const hookMap=new Map();window.Hooks={on:(k,f)=>{hookMap.set(k,[...(hookMap.get(k)??[]),f]);},once:()=>{}};
window.game={user:{id:'GM',isGM:true,can:()=>true,targets:new Set()},users:new Collection({id:'GM',isGM:true,name:'GM'},{id:'p1',isGM:false,name:'Alice'}),actors:new Collection(),journal:new Collection(),scenes:new Collection(),modules:new Map(),settings:{get:()=>undefined},alteredCarbon:{openCharacterCreator:()=>results.created.push('creator')}};
window.Roll=class{constructor(formula){this.formula=formula;}async evaluate(){const m=this.formula.match(/(\d+)d(\d+)/);this.total=m?Number(m[1])*3:0;this.dice=[{results:[{result:3}]}];return this;}};
window.ChatMessage={getSpeaker:()=>({}),getWhisperRecipients:()=>[],implementation:{create:async data=>{results.messages.push(data);return{id:'message1'};}}};
const skills=await(await fetch('systems/altered-carbon-rpg/data/core-skills.json')).json();
let n=0;function set(obj,path,value){const parts=path.split('.');let cur=obj;for(const k of parts.slice(0,-1))cur=cur[k]??={};cur[parts.at(-1)]=copy(value);}
window.actor={id:'actor1',uuid:'Actor.actor1',type:'character',isOwner:true,name:'Nia Calder',img:'data:image/svg+xml,'+encodeURIComponent('<svg xmlns="http://www.w3.org/2000/svg" width="100" height="100"><rect width="100" height="100" fill="#183442"/><circle cx="50" cy="32" r="19" fill="#346276"/><path d="M15 100 Q12 58 50 58 Q88 58 85 100" fill="#346276"/></svg>'),system:{identity:{trueName:'Nia Calder',archetype:'Criminal',variant:'standard',dhfAge:45},attributes:{strength:30,perception:30,empathy:30,willpower:30,acuity:30,intelligence:30},resources:{stackPoints:{value:200,max:200},health:{value:7,max:18},ego:{value:9,max:30},wounds:{value:2,max:30},influence:{value:4,max:5}},stackState:'intact',sleeveState:'healthy',egoState:'stable',wealth:2},ac:{bonuses:{strength:3,perception:3,empathy:3,willpower:3,acuity:3,intelligence:3},damageThreshold:30,speedDice:3,effectiveWealth:2},flags:{}};
actor.items=new Collection(...skills.map((s,i)=>({id:'s'+i,_id:'s'+i,uuid:'Actor.actor1.Item.s'+i,name:s.name,type:'skill',system:{...s,level:1,catalogId:s.id},skillDieSides:12})),{id:'sleeve',_id:'sleeve',type:'sleeve',name:'Natal sleeve',system:{sleeveType:'birth',status:'active',strength:30,perception:30,healthMax:18}},{id:'keepsake',_id:'keepsake',type:'equipment',name:'Keepsake',system:{quantity:1}});
actor.toObject=()=>copy({system:actor.system,flags:actor.flags,items:actor.items.map(i=>({_id:i._id,name:i.name,type:i.type,system:i.system}))});actor.update=async patch=>{for(const[k,v]of Object.entries(patch))set(actor,k,v);return actor;};actor.updateEmbeddedDocuments=async(type,patches)=>{for(const p of patches){const item=actor.items.get(p._id);for(const[k,v]of Object.entries(p))if(k!=='_id')set(item,k,v);}return patches;};actor.createEmbeddedDocuments=async(type,rows)=>rows.map(r=>{const item={...copy(r),id:'new'+(++n),_id:'new'+n};actor.items.push(item);return item;});actor.deleteEmbeddedDocuments=async(type,ids)=>{actor.items=new Collection(...actor.items.filter(i=>!ids.includes(i.id)));};actor.sheet={render:()=>{}};game.actors.push(actor);
const [{ACCharacterCreator},{ACAdvancementWizard,openAdvancement},{ACActorSheet},directory,{ColdStorageBookConsole}]=await Promise.all([import('./systems/altered-carbon-rpg/module/character-creator.mjs'),import('./systems/altered-carbon-rpg/module/advancement-wizard.mjs'),import('./systems/altered-carbon-rpg/module/sheets.mjs'),import('./systems/altered-carbon-rpg/module/actor-directory.mjs'),import('./systems/altered-carbon-rpg/module/adventure-book.mjs')]);
window.classes={ACCharacterCreator,ACAdvancementWizard,ACActorSheet};game.alteredCarbon.openAdvancement=openAdvancement;window.directory=directory;directory.installCharacterDirectoryHooks();directory.addCharacterCreatorButton(new ActorDirectory(),document.querySelector('#directory'));
window.show=async(type,section)=>{let app;if(type==='creator'){app=new ACCharacterCreator();app._step=6;}else if(type==='advancement'){app=new ACAdvancementWizard({actor});app._section=section??'skills';}else if(type==='book')app=new ColdStorageBookConsole();else{app=new ACActorSheet({actor});app._tab='skills';}app.render();await app.ready;return true;};
window.checkDirectoryHooks=()=>{const root=document.createElement('div');for(const f of hookMap.get('renderApplicationV2')??[])f({documentName:'Actor',constructor:{name:'ACActorSheet'}},root);if(root.querySelector('[data-ac-character-creator]'))throw Error('Creator appeared on sheet');for(const f of hookMap.get('renderApplicationV2')??[])f({tabName:'actors'},root);if(root.querySelectorAll('[data-ac-character-creator]').length!==1)throw Error('Missing creator');for(const f of hookMap.get('renderApplicationV2')??[])f({tabName:'actors'},root);if(root.querySelectorAll('[data-ac-character-creator]').length!==1)throw Error('Duplicate creator');return true;};
await show('sheet');window.ready=true;
