import test,{beforeEach} from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
const clone=structuredClone;let serial=0;
function assign(obj,path,value){const parts=path.split('.');let cur=obj;for(const part of parts.slice(0,-1))cur=cur[part]??={};cur[parts.at(-1)]=clone(value);}
class Collection extends Array{get contents(){return this;}get(id){return this.find(x=>x.id===id);}static get [Symbol.species](){return Array;}}
class Doc{constructor(data){Object.assign(this,clone(data));this.id=data._id??`document${String(++serial).padStart(8,'0')}`;this._id=this.id;this.flags??={};this.ownership??={default:0};this.sheet={render:()=>{}};}async update(data){for(const [k,v]of Object.entries(data))assign(this,k,v);return this;}toObject(){const{sheet,...rest}=this;return clone(rest);}}
class Journal extends Doc{constructor(data){super(data);this.pages=new Collection(...(data.pages??[]).map(p=>new Doc(p)));}async createEmbeddedDocuments(type,data){assert.equal(type,'JournalEntryPage');const docs=data.map(p=>new Doc(p));this.pages.push(...docs);return docs;}}
class App{async _prepareContext(){return {};}render(){return this;}}
globalThis.foundry={utils:{deepClone:clone,escapeHTML:s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))},applications:{api:{ApplicationV2:App,HandlebarsApplicationMixin:c=>c},sidebar:{tabs:{}}}};
globalThis.fetch=async url=>{const name=url.split('/').at(-1);return {ok:true,json:async()=>JSON.parse(fs.readFileSync(new URL(`../../data/cold-storage/${name}`,import.meta.url)))};};
globalThis.ui={notifications:{info:()=>{},warn:()=>{}}};
const book=await import('../../module/adventure-book.mjs');
beforeEach(()=>{serial=0;const settings=new Map(),store=new Map();globalThis.game={user:{id:'GM',isGM:true},users:new Collection({id:'GM',isGM:true,name:'GM'},{id:'U1',isGM:false,name:'Alice'},{id:'U2',isGM:false,name:'Ben'}),folders:new Collection(),journal:new Collection(),actors:new Collection(),scenes:new Collection(),modules:new Map(),settings:{settings,register:(scope,key,data)=>{settings.set(`${scope}.${key}`,data);store.set(`${scope}.${key}`,clone(data.default));},registerMenu:()=>{},get:(s,k)=>store.get(`${s}.${k}`),set:async(s,k,v)=>{store.set(`${s}.${k}`,clone(v));}}};globalThis.Folder={create:async data=>{const d=new Doc(data);game.folders.push(d);return d;}};globalThis.JournalEntry={create:async data=>{const d=new Journal(data);game.journal.push(d);return d;}};globalThis.Actor={create:()=>{throw Error('Book import must not create Actors');}};book.registerBook();});
const id=doc=>doc.flags?.['cold-storage']?.sourceId;
test('runtime: imports all 96 journals into six child folders, resolving every UUID',async()=>{const result=await book.importAdventureBook({notify:false});assert.deepEqual(result,{created:96,updated:0,journals:96,bookJournals:74});assert.equal(game.folders.length,7);const targetIds=new Set(game.journal.map(j=>j.id));for(const j of game.journal){assert.equal(j.pages.length,1);const html=j.pages[0].text.content;assert.doesNotMatch(html,/\[\[[^\]]+\]\]/);for(const m of html.matchAll(/@UUID\[JournalEntry\.([^\]]+)\]/g))assert.ok(targetIds.has(m[1]));}assert.equal(game.settings.get('altered-carbon-rpg','coldStorageBookVersion'),'1.1.1');});
test('runtime: unchanged repeated and concurrent imports do not duplicate journals',async()=>{await Promise.all([book.importAdventureBook(),book.importAdventureBook()]);const ids=game.journal.map(j=>j.id);const r=await book.importAdventureBook();assert.equal(r.created,0);assert.equal(r.updated,0);assert.equal(game.journal.length,96);assert.deepEqual(game.journal.map(j=>j.id),ids);});
test('runtime: source IDs from older module are reused and edited content is recovered',async()=>{const old=await JournalEntry.create({name:'Older opening',pages:[{name:'Old content',text:{content:'My played-session notes'},ownership:{default:3}}],ownership:{default:3},flags:{'cold-storage':{sourceId:'G00'}}});const originalId=old.id;await book.importAdventureBook();assert.equal(game.journal.filter(j=>id(j)==='G00').length,1);assert.equal(game.journal.find(j=>id(j)==='G00').id,originalId);const recovery=game.journal.find(j=>id(j).startsWith('REC-G00-'));assert.equal(recovery.pages[0].text.content,'My played-session notes');assert.equal(recovery.ownership.U1,0);assert.equal(old.ownership.default,0);assert.equal(old.pages[0].ownership.default,-1);});
test('runtime: extra user pages survive upgrades while GM-only grants are revoked',async()=>{await book.importAdventureBook();const j=game.journal.find(j=>id(j)==='G00');await j.createEmbeddedDocuments('JournalEntryPage',[{name:'My prep notes',text:{content:'Keep this custom page'},ownership:{default:3,U1:3}}]);await book.importAdventureBook();assert.equal(j.pages.length,2);assert.equal(j.pages[1].text.content,'Keep this custom page');assert.equal(j.pages[1].ownership.default,-1);assert.equal(j.pages[1].ownership.U1,-1);});
test('runtime: all spoilers begin hidden while designated public primers are visible',async()=>{await book.importAdventureBook();for(const j of game.journal){const f=j.flags['cold-storage'];assert.equal(j.ownership.U1,f.visibility==='public'?2:0);assert.equal(j.ownership.U2,f.visibility==='public'?2:0);}assert.equal(game.journal.filter(j=>j.flags['cold-storage'].visibility==='public').length,18);});
test('runtime: private cards require named players and disclose no other journal',async()=>{await book.importAdventureBook();const card=game.journal.find(j=>j.flags['cold-storage'].bookCategory==='personal');await assert.rejects(book.revealBookEntry(id(card),'everyone'),/explicit/);await book.revealBookEntry(id(card),['U1']);assert.equal(card.ownership.U1,2);assert.equal(card.ownership.U2,0);await book.importAdventureBook();assert.equal(card.ownership.U1,2);assert.equal(card.ownership.U2,0);for(const j of game.journal.filter(j=>['gm','reference'].includes(j.flags['cold-storage'].bookCategory)))assert.equal(j.ownership.U1,0);});
test('runtime: evidence can be revealed without exposing unrelated evidence',async()=>{await book.importAdventureBook();const cards=game.journal.filter(j=>j.flags['cold-storage'].bookCategory==='handout');await book.revealBookEntry(id(cards[0]),'everyone');assert.equal(cards[0].ownership.U1,2);assert.equal(cards[0].ownership.U2,2);assert.equal(cards[1].ownership.U1,0);await assert.rejects(book.revealBookEntry('G00','everyone'),/Only evidence/);});
test('runtime: book-only imports preserve Actors and existing custom scene links',async()=>{const actor=new Doc({name:'Played PC',system:{health:7,sp:24},flags:{'cold-storage':{sourceId:'PC01'}}});actor.update=()=>{throw Error('Actor mutation');};game.actors.push(actor);const custom=new Doc({name:'Custom link',journal:'custom-id',flags:{'cold-storage':{sourceId:'SCENE-WARD'}}}),empty=new Doc({name:'Empty link',journal:null,flags:{'cold-storage':{sourceId:'SCENE-RAINLINE'}}});game.scenes.push(custom,empty);await book.importAdventureBook();assert.equal(game.actors.length,1);assert.equal(actor.system.health,7);assert.equal(actor.system.sp,24);assert.equal(custom.journal,'custom-id');assert.equal(empty.journal,game.journal.find(j=>id(j)==='G10').id);});
test('runtime: non-GMs cannot import, reveal or alter counters',async()=>{game.user={id:'U1',isGM:false};await assert.rejects(book.importAdventureBook(),/Only a GM/);await assert.rejects(book.revealBookEntry('H01','everyone'),/Only a GM/);await assert.rejects(book.changeBookCounter('heat',1),/Only a GM/);assert.equal(game.journal.length,0);});
test('runtime: counters persist through imports and respect bounds',async()=>{await book.changeBookCounter('heat',6);await book.changeBookCounter('fray',-6,'PC01');await book.importAdventureBook();const state=game.settings.get('altered-carbon-rpg','coldStorageBookState');assert.equal(state.heat,6);assert.equal(state.fray.PC01,0);await assert.rejects(book.changeBookCounter('unknown',1),/Unknown/);});
test('runtime: active optional-module counters use the shared settings instead of resetting',async()=>{game.modules.set('cold-storage',{active:true});game.settings.register('cold-storage','bookState',{default:{heat:4,renewal:2,proof:1,control:0,people:0,fray:{PC01:5}}});game.settings.register('cold-storage','bookVersion',{default:'1.1.0'});await book.importAdventureBook();assert.equal(game.settings.get('cold-storage','bookState').heat,4);await book.changeBookCounter('fray',1,'PC01');assert.equal(game.settings.get('cold-storage','bookState').fray.PC01,6);assert.equal(game.settings.get('cold-storage','bookVersion'),'1.1.1');});
