import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import {quoteAdvancement,applyAdvancement,advancementSnapshot,snapshotFingerprint,attributeValue,commonalityFor} from '../../module/advancement.mjs';
const SYS='altered-carbon-rpg',copy=v=>JSON.parse(JSON.stringify(v));
const traits=JSON.parse(fs.readFileSync(new URL('../../data/trait-catalog.json',import.meta.url))).traits;
function state(sp=200){return {system:{identity:{archetype:'Criminal',dhfAge:40,variant:'standard'},attributes:{strength:30,perception:30,empathy:30,willpower:30,acuity:30,intelligence:30},resources:{stackPoints:{value:sp,max:200},health:{value:7,max:18},ego:{value:9,max:30},wounds:{value:4,max:30},influence:{value:2,max:4}},wealth:2},flags:{},items:[{_id:'skill1',name:'Detection',type:'skill',system:{catalogId:'detection',attribute:'perception',level:1,specialisations:''}},{_id:'sleeve1',name:'My Sleeve',type:'sleeve',system:{sleeveType:'birth',status:'active',strength:30,perception:30,healthMax:18}},{_id:'gear1',name:'Keepsake',type:'equipment',system:{quantity:1}},{_id:'rel1',name:'Old Friend',type:'relationship',system:{revealState:'confirmed'}}]};}
function set(obj,path,value){const keys=path.split('.'),last=keys.pop();let target=obj;for(const k of keys)target=target[k]??={};target[last]=copy(value);}
function actor(data=state()){
  const a={_data:copy(data),id:'testActor',uuid:'Actor.testActor',type:'character',isOwner:true,name:'Tester',get system(){return this._data.system;},get flags(){return this._data.flags;},toObject(){return copy(this._data);},
    async update(patch){if(this.failActor)throw new Error('Simulated Actor write failure');for(const[k,v]of Object.entries(patch))set(this._data,k,v);return this;},
    async updateEmbeddedDocuments(type,patches){if(this.failItem){this.failItem=false;throw new Error('Simulated Item write failure');}for(const p of patches){const item=this._data.items.find(i=>i._id===p._id);assert.ok(item);for(const[k,v]of Object.entries(p))if(k!=='_id')set(item,k,v);}return patches;},
    async createEmbeddedDocuments(type,items){if(this.failCreate)throw new Error('Simulated creation failure');return items.map((i,n)=>{const id=`new${this._data.items.length+n}`;this._data.items.push({...copy(i),_id:id});return{id};});},
    async deleteEmbeddedDocuments(type,ids){this._data.items=this._data.items.filter(i=>!ids.includes(i._id));}
  };return a;
}
globalThis.game={user:{id:'player',isGM:false}};
globalThis.Roll=class{constructor(formula){this.formula=formula;}async evaluate(){this.total=Number(this.formula.split('d')[0])*3;return this;}};

test('advancement quotes chained skill levels at the existing SP costs',()=>{const q=quoteAdvancement(state(),[{kind:'skill',itemId:'skill1'},{kind:'skill',itemId:'skill1'}]);assert.equal(q.total,70);assert.equal(q.after,130);assert.equal(q.state.items[0].system.level,3);});
test('all requests are validated before any purchase is committed',()=>{assert.throws(()=>quoteAdvancement(state(69),[{kind:'skill',itemId:'skill1'},{kind:'skill',itemId:'skill1'}]),/Not enough/);assert.equal(state().items[0].system.level,1);});
test('maximum skills, unknown types and foreign skill IDs are rejected',()=>{const s=state();s.items[0].system.level=5;assert.throws(()=>quoteAdvancement(s,[{kind:'skill',itemId:'skill1'}]),/maximum/);assert.throws(()=>quoteAdvancement(s,[{kind:'skill',itemId:'anotherActorsItem'}]),/no longer/);assert.throws(()=>quoteAdvancement(s,[{kind:'xp'}]),/Unknown/);});
test('attribute spending rejects fractions, negatives, NaN and cap overflow',()=>{for(const v of [0,-1,1.5,NaN,Infinity])assert.throws(()=>quoteAdvancement(state(),[{kind:'attribute',attribute:'willpower',sp:v}]),/whole/);assert.throws(()=>quoteAdvancement(state(),[{kind:'attribute',attribute:'willpower',sp:21}]),/at most/);});
test('Attribute caps follow sleeve types and explicit overrides',()=>{const s=state();s.items[1].system.sleeveType='synthetic-low';assert.equal(quoteAdvancement(s,[{kind:'attribute',attribute:'strength',sp:1}]).steps[0].cap,40);s.flags[SYS]={advancementCaps:{willpower:60}};assert.equal(quoteAdvancement(s,[{kind:'attribute',attribute:'willpower',sp:1}]).steps[0].cap,60);});
test('specialisation costs count existing explicit and inline entries without duplicates',()=>{const s=state();s.items[0].system.specialisations='Tracking; Forensics';s.items.push({_id:'spec1',name:'Forensics',type:'specialisation',system:{skill:'Detection'}});assert.equal(quoteAdvancement(s,[{kind:'specialisation',itemId:'skill1',name:'Counter-surveillance'}]).total,25);assert.throws(()=>quoteAdvancement(s,[{kind:'specialisation',itemId:'skill1',name:'tracking'}]),/already/);});
test('Trait prerequisite checks reject skipping tiers and allow the installed common-tree progression',()=>{const tier2=traits.find(t=>t.tree==='Crime'&&t.tier===2);assert.throws(()=>quoteAdvancement(state(),[{kind:'trait',catalogId:tier2.id}],{traits}),/lower-tier/);const tier1=traits.find(t=>t.tree==='Crime'&&t.branch===tier2.branch&&t.tier===1);const q=quoteAdvancement(state(),[{kind:'trait',catalogId:tier1.id},{kind:'trait',catalogId:tier2.id}],{traits});assert.equal(q.total,16);assert.equal(q.steps[0].unlockCost,1);assert.equal(q.steps[1].unlockCost,0);});
test('Civilian Commonality is explicit instead of invented',()=>{const s=state();s.system.identity.archetype='Civilian';const t=traits.find(t=>t.tier===1);assert.throws(()=>quoteAdvancement(s,[{kind:'trait',catalogId:t.id}],{traits}),/Commonality/);const q=quoteAdvancement(s,[{kind:'trait',catalogId:t.id,confirmCommonality:true,commonality:'common'}],{traits});assert.equal(q.total,6);assert.equal(q.state.flags[SYS].traitCommonality[t.tree],'common');});
test('known archetype and older Praxis Commonalities remain source-derived',()=>{assert.equal(commonalityFor({archetype:'Criminal',dhfAge:30},'Crime'),'common');assert.equal(commonalityFor({archetype:'Technician',dhfAge:30},'Combat'),'anomaly');assert.equal(commonalityFor({archetype:'Civilian',dhfAge:110},'Praxis'),'common');});
test('applying a skill advancement charges SP once and preserves resources, gear and relationships',async()=>{const a=actor(),before=a.toObject();const r=await applyAdvancement(a,[{kind:'skill',itemId:'skill1'}],{reason:'Session 2'});assert.equal(a.system.resources.stackPoints.value,180);assert.equal(a._data.items[0].system.level,2);for(const key of ['health','ego','wounds','influence'])assert.deepEqual(a.system.resources[key],before.system.resources[key]);assert.deepEqual(a._data.items.slice(1),before.items.slice(1));assert.equal(a.flags[SYS].advancementHistory.length,1);assert.equal(r.entry.spent,20);});
test('physical advancement updates the current sleeve; mental advancement updates the persistent DHF',async()=>{const a=actor();await applyAdvancement(a,[{kind:'attribute',attribute:'strength',sp:2},{kind:'attribute',attribute:'willpower',sp:2}]);assert.equal(a._data.items[1].system.strength,36);assert.equal(a.system.attributes.strength,30);assert.equal(a.system.attributes.willpower,36);assert.equal(a.system.resources.stackPoints.value,196);});
test('rolled gains stop at caps and record the actual change',async()=>{const s=state();s.system.attributes.willpower=49;const a=actor(s);const{entry}=await applyAdvancement(a,[{kind:'attribute',attribute:'willpower',sp:1}]);assert.equal(a.system.attributes.willpower,50);assert.equal(entry.steps[0].rolled,3);assert.equal(entry.steps[0].gain,1);});
test('specialisations and Traits are purchased, not silently added for free',async()=>{const a=actor();await applyAdvancement(a,[{kind:'specialisation',itemId:'skill1',name:'Surveillance'}]);assert.equal(a.system.resources.stackPoints.value,185);assert.ok(a._data.items.some(i=>i.name==='Surveillance'));await assert.rejects(()=>applyAdvancement(a,[{kind:'specialisation',itemId:'skill1',name:'Surveillance'}]),/already/);assert.equal(a.system.resources.stackPoints.value,185);});
test('confirmed Civilian tree Commonality persists after purchase',async()=>{const s=state();s.system.identity.archetype='Civilian';const a=actor(s),t=traits.find(t=>t.tier===1);await applyAdvancement(a,[{kind:'trait',catalogId:t.id,commonality:'common',confirmCommonality:true}],{traits});assert.equal(a.flags[SYS].traitCommonality[t.tree],'common');});
test('failed final Actor write rolls back embedded skills and new items without charging SP',async()=>{const a=actor(),before=a.toObject();a.failActor=true;await assert.rejects(()=>applyAdvancement(a,[{kind:'skill',itemId:'skill1'},{kind:'specialisation',itemId:'skill1',name:'Tracking'}]),/Actor write/);assert.deepEqual(a.toObject(),before);});
test('failed Item creation rolls back earlier embedded changes',async()=>{const a=actor(),before=a.toObject();a.failCreate=true;await assert.rejects(()=>applyAdvancement(a,[{kind:'skill',itemId:'skill1'},{kind:'specialisation',itemId:'skill1',name:'Tracking'}]),/creation failure/);assert.deepEqual(a.toObject(),before);});
test('stale confirmed quotes are rejected without modifying the actor',async()=>{const a=actor(),fingerprint=snapshotFingerprint(advancementSnapshot(a));a._data.system.resources.stackPoints.value=180;const before=a.toObject();await assert.rejects(()=>applyAdvancement(a,[{kind:'skill',itemId:'skill1'}],{expectedFingerprint:fingerprint}),/changed/);assert.deepEqual(a.toObject(),before);});
test('non-owners cannot advance someone else or spend their points',async()=>{const a=actor();a.isOwner=false;await assert.rejects(()=>applyAdvancement(a,[{kind:'skill',itemId:'skill1'}]),/owner/);assert.equal(a.system.resources.stackPoints.value,200);});
test('same-client duplicate submissions are blocked while the first request runs',async()=>{const a=actor();let finish;const update=a.update.bind(a);a.update=patch=>new Promise(resolve=>{finish=async()=>{await update(patch);resolve(a);};});const first=applyAdvancement(a,[{kind:'skill',itemId:'skill1'}]);await Promise.resolve();await Promise.resolve();await assert.rejects(()=>applyAdvancement(a,[{kind:'skill',itemId:'skill1'}]),/already being applied/);await finish();await first;assert.equal(a.system.resources.stackPoints.value,180);});
